baseURL = 'https://status.blackpiratex.com/'
languageCode = 'en-us'
title = 'Status By BlackPirateX'
theme = 'minimalbp'




[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'Box'


[params]
  author = 'BlackPirateX'
  description = "Quick one liner thoughts, that comes to my mind."
  tags = 'tags'
  catagories = 'catagories'
