baseURL = 'https://status.blackpiratex.com/'
languageCode = 'en-us'
title = 'Status By BlackPirateX'
theme = 'minimalbp'


[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 10
  resampleFilter = 'Box'

  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = ''
    includeFields = ''


[params]
  author = 'BlackPirateX'
  description = "Quick one liner thoughts, that comes to my mind."
  tags = 'tags'
  catagories = 'catagories'


[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]
